GET http://localhost:3001/api/notes

###

DELETE http://localhost:3001/api/notes/4

###
POST http://localhost:3001/api/notes
Content-Type:application/json

{
        "content":"VS Code REST client is pretty usefull",
        "important":"false"
}